CREATE TABLE `budget_allocation` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`date` varchar(10) NOT NULL,
	`category1` decimal(10,2) DEFAULT '0',
	`category2` decimal(10,2) DEFAULT '0',
	`category3` decimal(10,2) DEFAULT '0',
	`category4` decimal(10,2) DEFAULT '0',
	`category5` decimal(10,2) DEFAULT '0',
	`category6` decimal(10,2) DEFAULT '0',
	`category7` decimal(10,2) DEFAULT '0',
	`category8` decimal(10,2) DEFAULT '0',
	`category9` decimal(10,2) DEFAULT '0',
	`category10` decimal(10,2) DEFAULT '0',
	`totalBudget` decimal(10,2) DEFAULT '0',
	`totalAllocated` decimal(10,2) DEFAULT '0',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `budget_allocation_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `daily_metrics` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`date` varchar(10) NOT NULL,
	`faithScore` decimal(3,1) DEFAULT '0',
	`hustlePercentage` decimal(5,2) DEFAULT '0',
	`loveScore` decimal(3,1) DEFAULT '0',
	`mindPillar` decimal(3,1) DEFAULT '5',
	`bodyPillar` decimal(3,1) DEFAULT '5',
	`soulPillar` decimal(3,1) DEFAULT '5',
	`moneyPillar` decimal(3,1) DEFAULT '5',
	`powerPillar` decimal(3,1) DEFAULT '5',
	`respectPillar` decimal(3,1) DEFAULT '5',
	`consistencyPillar` decimal(3,1) DEFAULT '5',
	`happinessPillar` decimal(3,1) DEFAULT '5',
	`recoveryPillar` decimal(3,1) DEFAULT '5',
	`impactPillar` decimal(3,1) DEFAULT '5',
	`mindIntelligence` decimal(5,2) DEFAULT '0',
	`bodyIntelligence` decimal(5,2) DEFAULT '0',
	`soulIntelligence` decimal(5,2) DEFAULT '0',
	`powerScore` decimal(8,2) DEFAULT '0',
	`streakMultiplier` decimal(5,2) DEFAULT '1',
	`burnoutRisk` decimal(5,2) DEFAULT '0',
	`faithDecayRisk` decimal(5,2) DEFAULT '0',
	`momentumStatus` varchar(20) DEFAULT 'neutral',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `daily_metrics_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `intelligence_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`date` varchar(10) NOT NULL,
	`mindIntelligence` decimal(5,2) DEFAULT '0',
	`bodyIntelligence` decimal(5,2) DEFAULT '0',
	`soulIntelligence` decimal(5,2) DEFAULT '0',
	`overallIntelligence` decimal(5,2) DEFAULT '0',
	`burnoutRisk` decimal(5,2) DEFAULT '0',
	`faithDecayRisk` decimal(5,2) DEFAULT '0',
	`momentumStatus` varchar(20) DEFAULT 'neutral',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `intelligence_history_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `user_progression` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`currentLevel` int NOT NULL DEFAULT 1,
	`totalPoints` int NOT NULL DEFAULT 0,
	`pointsToNextGate` int NOT NULL DEFAULT 40,
	`currentStreak` int NOT NULL DEFAULT 0,
	`longestStreak` int NOT NULL DEFAULT 0,
	`lastActiveDate` varchar(10),
	`totalCredits` decimal(10,2) DEFAULT '0',
	`spentCredits` decimal(10,2) DEFAULT '0',
	`unlockedGates` json DEFAULT ('[]'),
	`intelligenceTier` varchar(20) DEFAULT 'novice',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `user_progression_id` PRIMARY KEY(`id`),
	CONSTRAINT `user_progression_userId_unique` UNIQUE(`userId`)
);
